# Generated by Django 4.1.5 on 2023-04-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_peliculas', '0011_alter_critica_puntaje_alter_critica_resenia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critica',
            options={'ordering': ['-id']},
        ),
    ]
